vmax: 1.5
chatting probability: 0.4
tell story probability: 0.4
group talking probability: 0.4
talking and walking probability: 0.4
requesting service probability: 0.014
requesting guide probability: 0.0
requesting follower probability: 0.0
max talking distance: 3.0
max servicing radius: 7.0
talking base time: 20.0
tell story base time: 20.0
group talking base time: 20.0
talking and walking base time: 20.0
receiving service base time: 20.0
requesting service base time: 20.0
use danger zone: 0.0
